name: hhbbgg-flow
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - ipython
  - coffea~=0.7
  - uproot~=4.3
  - pyaml
  - xrootd
  - numba
  - pyarrow
  - pandas
  - rich
  - matplotlib~=3.8
  - jupyterlab~=4.0
  - vector
  - conda-pack
  - tqdm
  - numpy~=1.23
  - pandas~=2.2
  - cuda-python~=11.8
  - ruamel.yaml
  - xgboost==1.5.1
  - dask
  - distributed
  - dask-jobqueue
  - sphinx
  - breathe
  - sphinx_rtd_theme
  - sphinx-argparse
  - nbsphinx
  - ipywidgets
  - nbconvert>=5.5.0
  - jinja2>=3.0.3
  - pandoc
  - pytorch
  - torchvision
  - awkward>=1.10
  - hist~=2.7
  - mplhep~=0.3
  - pyarrow~=14.0
  - vector~=1.1
  - torchvision
  - torchaudio
  - scikit-learn~=1.4
  - scikit-optimize>=0.10
  - xgboost~=1.5
  - pip:
    - zuko==1.0.1
    